FileVersion = 1

[Project]
Name = "cjson-beef"
TargetType = "BeefLib"
StartupObject = "cjson.Program"
DefaultNamespace = "cjson"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\cjson_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\cjson.lib"]
