FileVersion = 1

[Project]
Name = "cjson-beef"
TargetType = "BeefLib"
StartupObject = "cjson.Program"
DefaultNamespace = "cjson"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\windows\\cjsond.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\cjson.lib"]
